# Generated by Django 5.0.1 on 2024-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0003_transcriberesult'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriberesult',
            name='redacted_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
