# Generated by Django 5.0.1 on 2024-01-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_transcriberesult_redacted_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriberesult',
            name='redacted_uri',
        ),
        migrations.AddField(
            model_name='transcriberesult',
            name='redacted',
            field=models.BooleanField(default=False),
        ),
    ]
