# Generated by Django 5.0.1 on 2024-01-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_remove_transcriberesult_redacted_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriberesult',
            name='redacted',
            field=models.CharField(max_length=20),
        ),
    ]
