# Generated by Django 5.0.1 on 2024-01-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_transcriberesult_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=1000)),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub.langcode')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub.transcriberesult')),
            ],
        ),
    ]
