# Generated by Django 5.0.1 on 2024-01-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0009_translateresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainTranscribeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=1000)),
                ('transcribe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sub.transcriberesult')),
            ],
        ),
    ]
